# Generated by Django 5.2.10 on 2026-01-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilm',
            name='preference',
            field=models.CharField(blank=True, choices=[('liked', 'I liked it'), ('ok', 'It was ok'), ('disliked', "I didn't like it")], max_length=10, null=True),
        ),
    ]
