# Generated by Django 5.2.10 on 2026-02-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userfilm_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
