# Generated by Django 5.2.10 on 2026-02-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_film_poster_path_film_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilm',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfilm',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
