# Generated by Django 5.2.10 on 2026-02-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userfilm_poster_path_userfilm_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
