# Generated by Django 5.2.3 on 2026-02-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pairwisecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilm',
            name='bt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userfilm',
            name='elo',
            field=models.FloatField(default=1500.0),
        ),
    ]
