# Generated by Django 5.2.3 on 2026-02-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userfilm_bt_userfilm_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilm',
            name='elo',
            field=models.FloatField(default=0.0),
        ),
    ]
